package com.testspace.sampley;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Jewel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private int offer;

	public Jewel() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public int getOffer() {
		return this.offer;
	}

	public void setOffer(int offer) {
		this.offer = offer;
	}

	public Jewel(java.lang.String type, int offer) {
		this.type = type;
		this.offer = offer;
	}

}