package com.testspace.sampley;

rule "Set Offer for Diamond"
ruleflow-group "gold-offer-group-1"
when
    data : Jewel(type == "diamond")
then
    data.setOffer(60);
    update(data);
end

rule "Set Offer for Gold"
ruleflow-group "gold-offer-group-1"
when
    data : Jewel(type == "gold")
then
    data.setOffer(10);
    update(data);
end

rule "Set Offer for Not Gold"
ruleflow-group "gold-offer-group-1"
when
    data : Jewel(type == null)
then
    data.setOffer(15);
    update(data);
end

rule "Set Offer for anything"
ruleflow-group "gold-offer-group-1"
when
    data : Jewel(type == "silver")
then
    data.setOffer(25);
    update(data);
end